---

- name: Enable IP forwarding
  replace:
    path: /etc/sysctl.conf
    regexp: '\#net\.ipv4\.ip_forward=[0-9]'
    replace: 'net.ipv4.ip_forward=1'
    backup: yes

- name: template NIC Config file
  template:
    src: nic.cf
    dest: /etc/network/interfaces
  notify:
    - restart
    - wait for restart

- name: template iptables Config file
  template:
    src: iptables.rules
    dest: /etc/iptables.rules

- name: Reload iptables
  shell: 'iptables-restore < /etc/iptables.rules'
