all:
  hosts:
    client:
      ansible_ssh_port: 4001
      hostname: '{{ hosts.client.hostname }}'
    ldap:
      ansible_ssh_port: 4002
      hostname: '{{ hosts.ldap.hostname }}'

    mail:
      ansible_ssh_port: 4003
      hostname: '{{ hosts.mail.hostname }}'
    gitlab:
      ansible_ssh_port: 4004
      hostname: '{{ hosts.gitlab.hostname }}'
    nginx:
      ansible_ssh_port: 4005
      hostname: '{{ hosts.nginx.hostname }}'
    preprod:
      ansible_ssh_port: 4006
      hostname: '{{ hosts.preprod.hostname }}'
    db-master:
      ansible_ssh_port: 4007
      hostname: '{{ hosts.db-master.hostname }}'
    db-slave:
      ansible_ssh_port: 4008
      hostname: '{{ hosts.db-slave.hostname }}'
    worker-1:
      ansible_ssh_port: 4009
      hostname: '{{ hosts.worker-1.hostname }}'
    worker-2:
      ansible_ssh_port: 4010
      hostname: '{{ hosts.worker-2.hostname }}'
    nginx-slave:
      ansible_ssh_port: 4014
      hostname: '{{ hosts.nginx-slave.hostname }}'
  children:
    network:
      hosts:
        gateway:
          ansible_ssh_port: 4222
          hostname: '{{ hosts.gateway.hostname }}'
        dhcp:
          ansible_ssh_port: 4253
          hostname: '{{ hosts.dhcp.hostname }}'
        dns:
          ansible_ssh_port: 4252
          hostname: '{{ hosts.dns.hostname }}'
        vpn:
          ansible_ssh_port: 4013
          hostname: '{{ hosts.vpn.hostname }}'
    health:
      hosts:
        shinken:
          ansible_ssh_port: 4011
          hostname: '{{ hosts.shinken.hostname }}'
        backup:
          ansible_ssh_port: 4012
          hostname: '{{ hosts.backup.hostname }}'
    tests:
      hosts:
        test-vm:
          ansible_ssh_port: 9999
          hostname: '{{ hosts.ldap.hostname }}'
        test-vm2:
          ansible_ssh_port: 9998
          hostname: '{{ hosts.gitlab.hostname }}'
  vars:
    ansible_ssh_host: 10.23.1.111
    host_key_checking: false

    

