---

- name: install basic packages
  apt:
    state: latest
    install_recommends: no
    name: '{{ item }}'
  loop:
    - postgresql-9.6
    - python-pip

- name: "Install psycopg2"
  pip: 
    name: psycopg2-binary

- name: create replication user
  become: true
  become_user: postgres
  postgresql_user:
    name: '{{ db.users.replication.user }}'
    password: '{{ db.users.replication.password }}'
    role_attr_flags: replication
  notify: "restart psql"

- name: copy config files
  copy:
    src: postgres/master/
    dest: /etc/postgresql/9.6/main/
  notify: "restart psql"

- name: template config files
  template:
    src: postgres/master/
    dest: /etc/postgresql/9.6/main/
  notify: "restart psql"

- name: create ssh directory
  file:
    state: directory
    path: /var/lib/postgresql/.ssh

- name: copy ssh postgres pv key
  copy:
    src: ssh/master.pv
    dest: /var/lib/postgresql/.ssh/id_rsa
  notify: "restart psql"

- name: copy ssh slave public key
  copy:
    src: ssh/slave.pub
    dest: /var/lib/postgresql/.ssh/authorized_keys
  notify: "restart psql"

- name: Include db_setup role
  include_role:
    name: db_setup
