---
# handlers
#
- name: restore iptables
  listen: "restore iptables"
  shell: "/sbin/iptables-restore < /etc/iptables.rules"

- name: restart
  listen: "restart"
  command: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
  async: 1
  poll: 0
  #ignore_errors: true

- name: wait for restart
  listen: "wait for restart"
  wait_for_connection:
    connect_timeout: 20
    sleep: 5
    delay: 5
    timeout: 60
